// <auto-generated />
using System;
using MTDemo.Sagas.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MTDemo.Sagas.Migrations
{
    [DbContext(typeof(SurveyImportSagaDbContext))]
    [Migration("20241010105800_RowVersionNullable")]
    partial class RowVersionNullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MTDemo.Sagas.SagaStateMachines.ConditionImportState", b =>
                {
                    b.Property<string>("ConditionId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Error")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsImported")
                        .HasColumnType("boolean");

                    b.HasKey("ConditionId");

                    b.HasIndex("CorrelationId");

                    b.ToTable("ConditionImportState");
                });

            modelBuilder.Entity("MTDemo.Sagas.SagaStateMachines.QuestionImportState", b =>
                {
                    b.Property<string>("QuestionId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Error")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsImported")
                        .HasColumnType("boolean");

                    b.HasKey("QuestionId");

                    b.HasIndex("CorrelationId");

                    b.ToTable("QuestionImportState");
                });

            modelBuilder.Entity("MTDemo.Sagas.SagaStateMachines.SurveyImportState", b =>
                {
                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid");

                    b.Property<string>("CurrentState")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid?>("GetImportDetailsRequestId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ImportStartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<DateTime?>("SurveyImportDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SurveyImportId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("SurveyPublishDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("CorrelationId");

                    b.ToTable("SurveyImportState");
                });

            modelBuilder.Entity("MTDemo.Sagas.SagaStateMachines.ConditionImportState", b =>
                {
                    b.HasOne("MTDemo.Sagas.SagaStateMachines.SurveyImportState", "SurveyImportState")
                        .WithMany("ConditionImportStates")
                        .HasForeignKey("CorrelationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SurveyImportState");
                });

            modelBuilder.Entity("MTDemo.Sagas.SagaStateMachines.QuestionImportState", b =>
                {
                    b.HasOne("MTDemo.Sagas.SagaStateMachines.SurveyImportState", "SurveyImportState")
                        .WithMany("QuestionImportStates")
                        .HasForeignKey("CorrelationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SurveyImportState");
                });

            modelBuilder.Entity("MTDemo.Sagas.SagaStateMachines.SurveyImportState", b =>
                {
                    b.Navigation("ConditionImportStates");

                    b.Navigation("QuestionImportStates");
                });
#pragma warning restore 612, 618
        }
    }
}
