// <auto-generated />
using System;
using MTDemo.Sagas.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace MTDemo.Sagas.Migrations
{
    [DbContext(typeof(SurveyImportSagaDbContext))]
    [Migration("20241003115137_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MTDemo.Sagas.SagaStateMachines.ConditionImportState", b =>
                {
                    b.Property<string>("ConditionId")
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR2(64)");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("Error")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("IsImported")
                        .HasColumnType("NUMBER(1)");

                    b.HasKey("ConditionId");

                    b.HasIndex("CorrelationId");

                    b.ToTable("ConditionImportState");
                });

            modelBuilder.Entity("MTDemo.Sagas.SagaStateMachines.QuestionImportState", b =>
                {
                    b.Property<string>("QuestionId")
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR2(64)");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("Error")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("IsImported")
                        .HasColumnType("NUMBER(1)");

                    b.HasKey("QuestionId");

                    b.HasIndex("CorrelationId");

                    b.ToTable("QuestionImportState");
                });

            modelBuilder.Entity("MTDemo.Sagas.SagaStateMachines.SurveyImportState", b =>
                {
                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("CurrentState")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR2(64)");

                    b.Property<DateTime?>("ImportStartDate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("RAW(8)");

                    b.Property<string>("SignedUri")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("NVARCHAR2(256)");

                    b.Property<DateTime?>("SurveyImportDate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime?>("SurveyPublishDate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.HasKey("CorrelationId");

                    b.ToTable("SurveyImportState");
                });

            modelBuilder.Entity("MTDemo.Sagas.SagaStateMachines.ConditionImportState", b =>
                {
                    b.HasOne("MTDemo.Sagas.SagaStateMachines.SurveyImportState", "SurveyImportState")
                        .WithMany("ConditionImportStates")
                        .HasForeignKey("CorrelationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SurveyImportState");
                });

            modelBuilder.Entity("MTDemo.Sagas.SagaStateMachines.QuestionImportState", b =>
                {
                    b.HasOne("MTDemo.Sagas.SagaStateMachines.SurveyImportState", "SurveyImportState")
                        .WithMany("QuestionImportStates")
                        .HasForeignKey("CorrelationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SurveyImportState");
                });

            modelBuilder.Entity("MTDemo.Sagas.SagaStateMachines.SurveyImportState", b =>
                {
                    b.Navigation("ConditionImportStates");

                    b.Navigation("QuestionImportStates");
                });
#pragma warning restore 612, 618
        }
    }
}
