// <auto-generated />
using System;
using MTDemo.Sagas.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace MTDemo.Sagas.Migrations
{
    [DbContext(typeof(SurveyImportStateDbContext))]
    [Migration("20241017171641_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MTDemo.Sagas.SurveyImport.QuestionImport", b =>
                {
                    b.Property<Guid>("SurveyImportId")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("QuestionId")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("Error")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("IsImported")
                        .HasColumnType("NUMBER(1)");

                    b.Property<int>("Sequence")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("SurveyImportId", "QuestionId");

                    b.ToTable("QuestionImport");
                });

            modelBuilder.Entity("MTDemo.Sagas.SurveyImport.SurveyImport", b =>
                {
                    b.Property<Guid>("SurveyImportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<string>("SurveyData")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("SurveyImportId");

                    b.ToTable("SurveyImports");
                });

            modelBuilder.Entity("MTDemo.Sagas.SurveyImport.QuestionImport", b =>
                {
                    b.HasOne("MTDemo.Sagas.SurveyImport.SurveyImport", null)
                        .WithMany("Questions")
                        .HasForeignKey("SurveyImportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MTDemo.Sagas.SurveyImport.SurveyImport", b =>
                {
                    b.Navigation("Questions");
                });
#pragma warning restore 612, 618
        }
    }
}
