// <auto-generated />
using System;
using MassTransit.EntityFrameworkCoreIntegration;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace MTDemo.JobConsumer.Migrations
{
    [DbContext(typeof(JobServiceSagaDbContext))]
    [Migration("20241008170948_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MassTransit.JobAttemptSaga", b =>
                {
                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("RAW(16)");

                    b.Property<int>("CurrentState")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime?>("Faulted")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("InstanceAddress")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<Guid>("JobId")
                        .HasColumnType("RAW(16)");

                    b.Property<int>("RetryAttempt")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("ServiceAddress")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime?>("Started")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<Guid?>("StatusCheckTokenId")
                        .HasColumnType("RAW(16)");

                    b.HasKey("CorrelationId");

                    b.HasIndex("JobId", "RetryAttempt")
                        .IsUnique();

                    b.ToTable("JobAttemptSaga");
                });

            modelBuilder.Entity("MassTransit.JobSaga", b =>
                {
                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("RAW(16)");

                    b.Property<Guid>("AttemptId")
                        .HasColumnType("RAW(16)");

                    b.Property<DateTime?>("Completed")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int>("CurrentState")
                        .HasColumnType("NUMBER(10)");

                    b.Property<TimeSpan?>("Duration")
                        .HasColumnType("INTERVAL DAY(8) TO SECOND(7)");

                    b.Property<DateTime?>("Faulted")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Job")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<Guid?>("JobRetryDelayToken")
                        .HasColumnType("RAW(16)");

                    b.Property<Guid?>("JobSlotWaitToken")
                        .HasColumnType("RAW(16)");

                    b.Property<TimeSpan?>("JobTimeout")
                        .HasColumnType("INTERVAL DAY(8) TO SECOND(7)");

                    b.Property<Guid>("JobTypeId")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("Reason")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("RetryAttempt")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("ServiceAddress")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime?>("Started")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime?>("Submitted")
                        .HasColumnType("TIMESTAMP(7)");

                    b.HasKey("CorrelationId");

                    b.ToTable("JobSaga");
                });

            modelBuilder.Entity("MassTransit.JobTypeSaga", b =>
                {
                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("RAW(16)");

                    b.Property<int>("ActiveJobCount")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("ActiveJobs")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("ConcurrentJobLimit")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("CurrentState")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Instances")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Name")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int?>("OverrideJobLimit")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime?>("OverrideLimitExpiration")
                        .HasColumnType("TIMESTAMP(7)");

                    b.HasKey("CorrelationId");

                    b.ToTable("JobTypeSaga");
                });
#pragma warning restore 612, 618
        }
    }
}
