// <auto-generated />
using System;
using MTDemo.Sagas.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace MTDemo.Sagas.Migrations.SurveyImportSagaDb
{
    [DbContext(typeof(SurveyImportSagaDbContext))]
    [Migration("20241017171651_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MTDemo.Sagas.SagaStateMachines.SurveyImportSagaState", b =>
                {
                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("CurrentState")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR2(64)");

                    b.Property<DateTime?>("ImportEndDate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime?>("ImportStartDate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("RAW(8)");

                    b.Property<int>("Success")
                        .HasColumnType("NUMBER(1)");

                    b.Property<DateTime?>("SurveyImportDate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime?>("SurveyPublishDate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.HasKey("CorrelationId");

                    b.ToTable("SurveyImportSagaState");
                });
#pragma warning restore 612, 618
        }
    }
}
